name: Build docker image, push to dockerhub
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-push-base-image:
    name: Build and deploy base image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get the tag version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: drailz/frn_rasperry
        tag_with_sha: true
        dockerfile: docker/Dockerfile